export const focuslyPhrases = [
  "Vamos lá, mais uma sessão de foco para avançar nos seus objetivos! 💪🚀",
  "Você está cada vez mais perto do seu objetivo! Continue com o foco total! 🎯🔥",
  "Mais uma rodada! Aproveite esses minutos e faça acontecer! ⏰💥",
  "Cada Pomodoro é um passo a mais na direção certa. Mantenha o ritmo! 🚶‍♂️✨",
  "Mente clara, foco firme! Essa sessão é sua para brilhar! 🌟🙌",
  "Sua jornada está em movimento! Continue com força total! 🌊🚀",
  "Vamos nessa, você está no controle do seu tempo e dos seus resultados! ⏳💼",
  "Mais um Pomodoro, mais um passo! Continue em frente! 🚀💪",
  "Nada pode te parar! Siga firme nessa sessão e conquiste o que precisa! 🎯🔥",
  "Esse é o seu momento de foco. Dê o seu melhor! 🧠✨",
  "Cada minuto conta! Aproveite essa sessão e mantenha a concentração! ⏰📈",
  "Seus resultados estão a cada sessão – mantenha a consistência! 🎯🚀",
  "Você já chegou até aqui, então siga em frente! Conquiste essa sessão! 💪⚡",
  "Energia renovada! Vamos aproveitar mais essa sessão para crescer! 🌱🔥",
  "O foco é a chave para o sucesso. Mantenha-se presente e produtivo! 🧘‍♂️🚀",
  "Mais uma rodada, mais uma oportunidade de fazer a diferença! 💥⏰",
  "Está no fluxo! Continue avançando e construindo seu progresso! 🏆✨",
  "A cada sessão você está mais perto do seu objetivo. Não pare agora! 🚀📈",
  "Respire fundo e mergulhe nessa sessão com tudo o que tem! 🌬️💪",
  "Você está criando o seu melhor com cada Pomodoro. Siga firme! 🏗️🚀",
  "É hora de brilhar novamente! Mantenha a energia e o foco! 🌟⏳",
  "Você já conquistou muito! Continue com esse ritmo vencedor! 🏆🎉",
  "Está focado? Ótimo! Use essa sessão para conquistar mais um passo! 🚀⚡",
  "Essa sessão é um presente para o seu progresso. Aproveite! 🎁💥",
  "Cada Pomodoro é uma vitória. Conquiste mais uma agora! 🏅🚀",
  "Aproveite essa sessão como uma chance de mostrar o seu melhor! 🎯💪",
  "Sua dedicação está moldando o seu sucesso. Continue com tudo! 🧱✨",
  "Pomodoro a pomodoro, você está construindo algo incrível! 🏗️💫",
  "Mantenha a disciplina e veja seu progresso florescer! 🌱⏰",
  "Mais uma sessão, mais uma chance de chegar mais perto da sua meta! 🎉🚀",
  "Você já está fazendo história com cada minuto de foco. Continue assim! 📜💪",
  "Essa sessão é mais um passo para o seu futuro. Dê o seu melhor! 🚀⚡",
  "Cada sessão de foco te leva um pouco mais além. Aproveite o momento! 🌌✨",
  "Sinta o progresso em cada sessão. Vamos com tudo! 🏆⏳",
  "Você tem o poder de transformar cada minuto em sucesso. Foque! 🎯🔥",
  "Mantenha-se presente e faça valer cada segundo dessa sessão! 🕰️💪",
  "Foco é tudo! Vamos juntos nessa e veja o progresso acontecer! 🚀💼",
  "Sua determinação é a chave. Aproveite essa sessão para abrir novas portas! 🚪✨",
  "Mais uma chance de crescer e aprender. Dê tudo de si! 🧠🚀",
  "Você está no caminho certo. Continue com garra nessa sessão! 💪🏅",
  "Cada Pomodoro é um tijolo na sua construção. Construa com dedicação! 🧱🚀",
  "O sucesso é uma soma de pequenas conquistas. Mantenha-se focado! 🎯🔥",
  "Vamos para mais uma? Esse é o seu momento de fazer a diferença! 🚀⏳",
  "Você está fazendo um ótimo trabalho. Continue com essa energia! 🌟📈",
  "Essa sessão é uma oportunidade para alcançar o seu melhor. Aproveite! 🌄💪",
  "A cada sessão você está mais preparado para o sucesso. Mantenha o ritmo! 🏆⚡",
  "É hora de crescer! Faça dessa sessão uma vitória pessoal. 🌱🎉",
  "Você está em pleno avanço. Continue construindo seus resultados! 🚀✨",
  "Mais uma sessão, mais um progresso. Vamos lá! 🎯📈",
  "Transforme essa sessão em uma conquista memorável. Dê o seu melhor! 💥🚀",
];
